version: '3.8'
services:
  prometheus:
    image: "prom/prometheus:v2.23.0"
    container_name: prometheus
    # replace with ip or dns of the server
    hostname: linuxacademy11c.mylabserver.com
    network_mode: host
    extra_hosts:
      - "nodeexporter:127.0.0.1"
      - "esexporter:127.0.0.1"
    restart: unless-stopped
    mem_limit: 4G
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
      - "./prometheus/:/etc/prometheus/"
      - "prometheus_data:/prometheus"
  nodeexporter:
    image: prom/node-exporter:v1.0.1
    container_name: nodeexporter
    network_mode: host
    user: root
    privileged: true
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    expose:
      - 9100
  esexporter:
    image: justwatch/elasticsearch_exporter:1.1.0
    container_name: esexporter
    network_mode: host
    volumes:
      - "./es-exporter/certs/:/certs"
    command:
     - '--es.uri=https://linuxacademy11c.mylabserver.com:9091'
     - '--es.ca=/certs/rootca.pem'
     - '--es.client-private-key=/certs/client-key.pem'
     - '--es.client-cert=/certs/client-cert.pem'
     - '--es.ssl-skip-verify'
    restart: unless-stopped
    expose:
      - 9114
  grafana:
    image: "grafana/grafana:7.3.5"
    container_name: grafana
    restart: unless-stopped
    mem_limit: 4G
    ports:
      - "80:3000"
    volumes:
      - "grafana_data:/var/lib/grafana"
    network_mode: host
    extra_hosts:
      - "prometheus:127.0.0.1"
    environment:
      # INSTALL SOME GRAFANA PLUGINS AUTOMATICALLY
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource,grafana-piechart-panel,novalabs-annotations-panel,vonage-status-panel,fetzerch-sunandmoon-datasource,natel-discrete-panel,natel-influx-admin-panel
      # YOU CAN CHANGE THE ADMIN PASSWORD USING THIS VARIABLE
      - GF_SECURITY_ADMIN_PASSWORD=admin
volumes:
  prometheus_data:
  grafana_data:
