version: '2.4'
services:
  prometheus:
    image: "prom/prometheus:v2.23.0"
    container_name: prometheus
    # REPLACE LOCALHOST WITH THE SERVER IP IF YOU WILL ACCESS IT FROM ANOTHER SERVER
    hostname: linuxacademy11c.mylabserver.com
    restart: unless-stopped
    mem_limit: 4G
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
      - "./prometheus/:/etc/prometheus/"
      - "prometheus_data:/prometheus"
    networks:
      - "monitoring"
  node-exporter:
    image: prom/node-exporter:v0.18.1
    container_name: nodeexporter
    user: root
    privileged: true
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    expose:
      - 9100
    networks:
     - "monitoring"
  elasticsearch_exporter:
    image: justwatch/elasticsearch_exporter:1.1.0
    command:
     - '--es.uri=http://host.docker.internal:9200'
    restart: unless-stopped
    expose:
      - 9114
    networks:
     - "monitoring"
     - "host"
  grafana:
    image: "grafana/grafana:7.3.5"
    container_name: grafana
    restart: unless-stopped
    mem_limit: 4G
    ports:
      - "80:3000"
    volumes:
      - "grafana_data:/var/lib/grafana"
    networks:
      - monitoring
    environment:
      # INSTALL SOME GRAFANA PLUGINS AUTOMATICALLY
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource,grafana-piechart-panel,novalabs-annotations-panel,vonage-status-panel,fetzerch-sunandmoon-datasource,natel-discrete-panel,natel-influx-admin-panel
      # YOU CAN CHANGE THE ADMIN PASSWORD USING THIS VARIABLE
      - GF_SECURITY_ADMIN_PASSWORD=admin
  
volumes:
  prometheus_data:
  grafana_data:
networks:
  monitoring:
  host:
    external:
      name: "host"
