# Global configuration
global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

# A list of scrape configurations.
scrape_configs:
  - job_name: "self-node-exporter"
    static_configs:
      - targets: ["nodeexporter:9100"]

  - job_name: "eslastic-node-exporter"
    static_configs:
      - targets: ["10.90.25.239:9100", "10.90.25.240:9100", "10.90.25.242:9100"]

  - job_name: "elasticsearch-exporter"
    static_configs:
      - targets: ["esexporter:9114"]
