# Global configuration
global:
  scrape_interval:     15s
  scrape_timeout: 10s
  evaluation_interval: 15s 

# A list of scrape configurations.
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'node'
    static_configs:
    - targets: ['nodeexporter:9100']
  - job_name: 'elasticsearch'
    static_configs:
    - targets: ['esexporter:9114']
  - job_name: 'node-2'
    static_configs:
    - targets: ['linuxacademy11c.mylabserver.com:9100']
  - job_name: 'kafka'
    static_configs:
    - targets: ['kafka:7071']