# Global configuration
global:
  scrape_interval:     15s
  scrape_timeout: 10s
  evaluation_interval: 15s 

# A list of scrape configurations.
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'node'
    static_configs:
    - targets: ['nodeexporter:9100']